project:
  type: book

book:
  title: "My FAIR Bioconductor"
  author:
    - name: "Kevin Rue"
      affiliation: "Oxford University"
      orcid: "0000-0003-3899-3872"
    - name: "Marisa Loach"
      affiliation: "The Open University"
      orcid: "0000-0001-6979-6930"
  date: "8/12/2026"
  chapters:
    - index.qmd
    - contributors.qmd
    - definitions.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
