project:
  type: book

book:
  title: "my-fair-bioconductor"
  author: "Norah Jones"
  date: "8/12/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



